title: Geonmin Kim
author: lifelongeek
email: ken.geonmin.kim@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Geonmin kim's interests and contributions 
show_excerpts: true # set to true to show excerpts on the homepage
url: "https://lifelongeek.github.io"
baseurl: "" #/texture


# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Geonmin Kim
  tagline: Research Engineer  
           at Clova Speech, Naver
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: false

  # generate social links in footer
  social_links:
    github:  lifelongeek
    linkedIn: in/geonmin-kim-642a8632
    CV: https://github.com/lifelongeek/lifelongeek.github.io/raw/master/CV_Geonmin_Kim_200127.pdf
    googlescholar: QRFMPSMAAAAJ
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
